// app/lib/sessionData.js

export const sessionData = {
  session_1_toetaps: {
    id: 'session_1_toetaps',
    title: 'Skill Session 1: Toe Taps',
    stadium: 'Wembley Stadium',
    location: 'London, UK',
    unlockXP: 0,
    video: '/videos/session_1_toetaps.mp4',
    thumbnail: '/videos/session_1_toetaps-thumbnail.jpg',
    img: '/stadiums/wembley.png',
    lat: 51.5560,
    lng: -0.2796,
  },

  session_2_ticktocks: {
    id: 'session_2_ticktocks',
    title: 'Skill Session 2: Tick Tocks',
    stadium: 'Old Trafford',
    location: 'Manchester, UK',
    unlockXP: 200,
    video: '/videos/session_2_ticktocks.mp4',
    // filename in your folder is capital JPG
    thumbnail: '/videos/session_2_ticktocks-thumbnail.JPG',
    img: '/stadiums/old-trafford.png',
    lat: 53.4631,
    lng: -2.2913,
  },

  session_3_ticktockstops: {
    id: 'session_3_ticktockstops',
    title: 'Skill Session 3: Tick Tock Stops',
    stadium: 'Signal Iduna Park',
    location: 'Dortmund, Germany',
    unlockXP: 300,
    video: '/videos/session_3_ticktockstops.mp4',
    thumbnail: '/videos/session_3_ticktockstops-thumbnail.JPG',
    img: '/stadiums/signal-iduna-park.png',
    lat: 51.4926,
    lng: 7.4519,
  },

  session_4_outside_take_stop: {
    id: 'session_4_outside_take_stop',
    title: 'Skill Session 4: Outside Take Stop',
    stadium: 'San Siro',
    location: 'Milan, Italy',
    unlockXP: 400,
    video: '/videos/session_4_outside-take-stop.mp4',
    // your file shows a hyphen before stop: take-stop.JPG
    thumbnail: '/videos/session_4_outside-take-stop.JPG',
    img: '/stadiums/san-siro.png',
    lat: 45.4781,
    lng: 9.1240,
  },

  session_5_tick_tock_sole_roll: {
    id: 'session_5_tick_tock_sole_roll',
    title: 'Skill Session 5: Tick Tock + Sole Roll',
    stadium: 'Parc des Princes',
    location: 'Paris, France',
    unlockXP: 500,
    video: '/videos/session_5_tick-tock-sole-roll.mp4',
    thumbnail: '/videos/session_5_tick-tock-sole-roll.JPG',
    img: '/stadiums/parc-des-princes.png',
    lat: 48.8414,
    lng: 2.2530,
  },

  session_6_tick_tock_outside_in: {
    id: 'session_6_tick_tock_outside_in',
    title: 'Skill Session 6: Tick Tock Outside-In',
    stadium: 'Camp Nou',
    location: 'Barcelona, Spain',
    unlockXP: 550,
    video: '/videos/session_6_tick-tock-outside-in.mp4',
    thumbnail: '/videos/session_6_tick-tock-outside-in.JPG',
    img: '/stadiums/camp-nou.png',
    lat: 41.3809,
    lng: 2.1228,
  },

  session_7_ball_roll_slides: {
    id: 'session_7_ball_roll_slides',
    title: 'Skill Session 7: Ball Roll Slides',
    stadium: 'Santiago Bernabéu',
    location: 'Madrid, Spain',
    unlockXP: 600,
    video: '/videos/session_7_ball_roll_slides.mp4',
    thumbnail: '/videos/session_7_ball_roll_slides.png',
    img: '/stadiums/bernabeu.png', // your stadium file uses the accent
    lat: 40.4531,
    lng: -3.6883,
  },

  session_8_tik_tok_roll_inside: {
    id: 'session_8_tik_tok_roll_inside',
    title: 'Skill Session 8: Tik Tok Roll Inside',
    stadium: 'Stade Vélodrome',
    location: 'Marseille, France',
    unlockXP: 700,
    video: '/videos/session_8_tik_tok_roll_inside.mp4',
    thumbnail: '/videos/session_8_tik_tok_roll_inside.png',
    img: '/stadiums/velodrome.png',
    lat: 43.2699,
    lng: 5.3958,
  },

  session_9_sticky_tape: {
    id: 'session_9_sticky_tape',
    title: 'Skill Session 9: Sticky Tape',
    stadium: 'Estádio do Dragão',
    location: 'Porto, Portugal',
    unlockXP: 800,
    video: '/videos/session_9_sticky_tape.mp4',
    thumbnail: '/videos/session_9_sticky_tape.png',
    img: '/stadiums/estadio-do-dragao.png',
    lat: 41.1621,
    lng: -8.5851,
  },

  session_10_tap_to_tape_inside: {
    id: 'session_10_tap_to_tape_inside',
    title: 'Skill Session 10: Tap to Tape Inside',
    stadium: 'Rose Bowl',
    location: 'Pasadena, USA',
    unlockXP: 900,
    video: '/videos/session_10_tap_to_tape_inside.mp4',
    thumbnail: '/videos/session_10_tap_to_tape_inside.png',
    img: '/stadiums/rose-bowl.png',
    lat: 34.1613,
    lng: -118.1675,
  },

  session_11_sticky_tape_sole_roll: {
    id: 'session_11_sticky_tape_sole_roll',
    title: 'Skill Session 11: Sticky Tape + Sole Roll',
    stadium: 'Allianz Arena',
    location: 'Munich, Germany',
    unlockXP: 1000,
    video: '/videos/session_11_sticky_tape_sole_roll.mp4',
    thumbnail: '/videos/session_11_sticky_tape_sole_roll.png',
    img: '/stadiums/allianz-arena.png',
    lat: 48.2188,
    lng: 11.6247,
  },

  session_12_sole_rolls: {
    id: 'session_12_sole_rolls',
    title: 'Skill Session 12: Sole Rolls',
    stadium: 'Celtic Park',
    location: 'Glasgow, Scotland',
    unlockXP: 1100,
    video: '/videos/session_12_sole_rolls.mp4',
    thumbnail: '/videos/session_12_sole_rolls.png',
    img: '/stadiums/celtic-park.png',
    lat: 55.8497,
    lng: -4.2055,
  },

  session_13_tick_tock_stop_outside: {
    id: 'session_13_tick_tock_stop_outside',
    title: 'Skill Session 13: Tick Tock Stop Outside',
    stadium: 'Ibrox Stadium',
    location: 'Glasgow, Scotland',
    unlockXP: 1200,
    video: '/videos/session_13_tick_tock_stop_outside.mp4',
    thumbnail: '/videos/session_13_tick_tock_stop_outside.png',
    img: '/stadiums/ibrox-stadium.png',
    lat: 55.8531,
    lng: -4.3090,
  },

  session_14_scissor_stop_direction_change: {
    id: 'session_14_scissor_stop_direction_change',
    title: 'Skill Session 14: Scissor Stop Direction Change',
    stadium: 'La Bombonera',
    location: 'Buenos Aires, Argentina',
    unlockXP: 1300,
    video: '/videos/session_14_scissor_stop_direction_change.mp4',
    thumbnail: '/videos/session_14_scissor_stop_direction_change.png',
    img: '/stadiums/la-bombonera.png',
    lat: -34.6356,
    lng: -58.3645,
  },

  session_15_continuous_scissors: {
    id: 'session_15_continuous_scissors',
    title: 'Skill Session 15: Continuous Scissors',
    stadium: 'FNB Stadium (Soccer City)',
    location: 'Johannesburg, South Africa',
    unlockXP: 1400,
    video: '/videos/session_15_continuous_scissors.mp4',
    thumbnail: '/videos/session_15_continuous_scissors.png',
    img: '/stadiums/fnb-stadium.png',
    lat: -26.2349,
    lng: 27.9820,
  },

  session_16_scissor_outside_take: {
    id: 'session_16_scissor_outside_take',
    title: 'Skill Session 16: Scissor Outside Take',
    stadium: 'Sydney Stadium',
    location: 'Sydney, Australia',
    unlockXP: 1500,
    video: '/videos/session_16_scissor_outside_take.mp4',
    thumbnail: '/videos/session_16_scissor_outside_take.png',
    img: '/stadiums/sydney.png',
    lat: -33.8911,
    lng: 151.2249,
  },

  session_17_continuous_reverse_stepover: {
    id: 'session_17_continuous_reverse_stepover',
    title: 'Skill Session 17: Continuous Reverse Stepover',
    stadium: 'Amsterdam Arena',
    location: 'Amsterdam, Netherlands',
    unlockXP: 1600,
    video: '/videos/session_17_continuous_reverse_stepover.mp4',
    thumbnail: '/videos/session_17_continuous_reverse_stepover.png',
    img: '/stadiums/amsterdam-arena.png',
    lat: 52.3143,
    lng: 4.9414,
  },

  session_18_toe_tap_special: {
    id: 'session_18_toe_tap_special',
    title: 'Skill Session 18: Toe Tap Special',
    stadium: 'MetLife Stadium',
    location: 'East Rutherford, USA',
    unlockXP: 1700,
    video: '/videos/session_18_toe_tap_special.mp4',
    thumbnail: '/videos/session_18_toe_tap_special.png',
    img: '/stadiums/metlife-stadium.png',
    lat: 40.8135,
    lng: -74.0745,
  },
};
